In [1]:
import numpy as np

# 1

Сгенерировать случайную матрицу:
* найти сумму элементов
* найти минимальный и максимальный элементы
* для каждой строки найти минимальный/максимальный элемент
* для каждого столбца найти минимальный/максимальный элемент
* найте среднее арифметическое всех чисел в матрице.

In [2]:
# Создание случайной матрицы
m = np.random.randint(-10, 10, (5, 6))

In [3]:

m

array([[  7,   6,  -9,   0, -10,   5],
       [  6,   9,  -3,  -3,  -9,  -6],
       [  3,  -6,  -1,  -9,   5,   6],
       [ -6,   6,  -3, -10,   3, -10],
       [-10,  -7,   3,   6,  -1,  -2]])

In [16]:
# numpy-решение 
def f1(m):
    r,c = m.shape
    """ rmat - матрица со случайными значениями """
    print(m)
    
    sum_, min_, max_ = m.sum(), m.min(), m.max() 
    print(f"sum = {sum_}")
    print(f"min = {min_}")
    print(f"max = {max_}")
    
    mins, maxs = np.zeros(r), np.zeros(r)
    mins = m.min(axis=0)
    maxs = m.max(axis=0)
    # for i in range(r):
        # mins[i] = m[i].min()
        # maxs[i] = m[i].max()


    print(f"mins in rows : {mins}")
    print(f"maxs in rows : {maxs}")
    
    mins, maxs = np.zeros(c), np.zeros(c)
    mins = m.min(axis=1)
    maxs = m.max(axis=1)
    # for i in range(c):
        # mins[i] = m[:, i].min()
        # maxs[i] = m[:, i].max()
    print(f"mins in cols : {mins}")
    print(f"maxs in cols : {maxs}")
    
    print(f"mean : {m.mean()}")

In [17]:
f1(m)

[[  7   6  -9   0 -10   5]
 [  6   9  -3  -3  -9  -6]
 [  3  -6  -1  -9   5   6]
 [ -6   6  -3 -10   3 -10]
 [-10  -7   3   6  -1  -2]]
sum = -40
min = -10
max = 9
mins in rows : [-10  -7  -9 -10 -10 -10]
maxs in rows : [7 9 3 6 5 6]
mins in cols : [-10  -9  -9 -10 -10]
maxs in cols : [7 9 6 6 6]
mean : -1.3333333333333333


# 2
Из массива $[1,2,3,\dots,N]$ получить массив $[1,0,0,2,0,0,3,0,0,...,N,0,0]$ 

In [47]:
def f2(N):
    arr2 = np.zeros(N*3, dtype=np.int32)    # модифицированный массив
    arr2[::3] = np.arange(1, N+1, dtype=np.int32)
    
    print(arr2)

In [48]:
f2(7)

[1 0 0 2 0 0 3 0 0 4 0 0 5 0 0 6 0 0 7 0 0]


# 3

Создать следующую квадратную матрицу:


$ \begin{bmatrix}
1 & 2 & 3 & 4 & 5 \\
6 & 7 & 8 & 9 & 10 \\
11 & 12 & 13 & 14 & 15 \\
16 & 17 & 18 & 19 & 20 \\
21 & 22 & 23 & 24 & 25 
\end{bmatrix}  $


и написать функцию, создающую такую квадратную матрицу для любого N

In [68]:
def f3(N):
    m = 1 + np.arange(N**2).reshape(N, N)
    print(m)

In [69]:
f3(6)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


# 4

Создать следующую квадратную матрицу:


$ \begin{bmatrix}
5 & 4 & 3 & 2 & 1 \\
4 & 5 & 4 & 3 & 2 \\
3 & 4 & 5 & 4 & 3 \\
2 & 3 & 4 & 5 & 4 \\
1 & 2 & 3 & 4 & 5 
\end{bmatrix}  $


и написать функцию, создающую такую квадратную матрицу для любого N

In [127]:
def f4(N):
    m = np.zeros((N, N))    # итоговая квадратная матрица
    for i in range(N):
        m += np.eye(N, k=(i-N))*(i)
    m += np.eye(N)*N
    for i in range(N):
        m += np.eye(N, k=(-i+N))*(i)
    print(m)

In [128]:
f4(6)

[[6. 5. 4. 3. 2. 1.]
 [5. 6. 5. 4. 3. 2.]
 [4. 5. 6. 5. 4. 3.]
 [3. 4. 5. 6. 5. 4.]
 [2. 3. 4. 5. 6. 5.]
 [1. 2. 3. 4. 5. 6.]]


# 5

Создать следующую квадратную матрицу:


$ \begin{bmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 5 \\
2 & 3 & 4 & 5 & 6 \\
3 & 4 & 5 & 6 & 7 \\
4 & 5 & 6 & 7 & 8 
\end{bmatrix}  $


и написать функцию, создающую такую матрицу для любого количества строк и столбцов.

In [158]:
def f5(r, c):
    # mm = np.arange(1, r+1).reshape(r, 1)
    m = np.arange(0, r).reshape(r, 1) + np.arange(1, r+1)
    # print(mm)
    # m = np.zeros((r, c))
    print(m-1)
    print(np.arange(0, r).reshape(r, 1))
    print(np.arange(0, r))

In [159]:
f5(5, 6)

[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]
[[0]
 [1]
 [2]
 [3]
 [4]]
[0 1 2 3 4]


In [138]:
f5(10000, 20000)

[[    0     1     2 ... 19997 19998 19999]
 [    1     2     3 ... 19998 19999 20000]
 [    2     3     4 ... 19999 20000 20001]
 ...
 [ 9997  9998  9999 ... 29994 29995 29996]
 [ 9998  9999 10000 ... 29995 29996 29997]
 [ 9999 10000 10001 ... 29996 29997 29998]]


# 6

Создать следующую квадратную матрицу:


$ \begin{bmatrix}
0 & 1 & 0\\
1 & 0 & 1\\
0 & 1 & 0\\
\end{bmatrix}  $


и написать функцию, создающую такую квадратную матрицу для любого N

In [205]:
def f6(N):
    m = np.zeros((N, N))    # итоговая прямоугольная матрица
    m[1::2,::2] = np.ones((N//2,  N//2+(N%2 == 1)))
    m[::2, 1::2] = np.ones((N//2 + (N%2 == 1), N//2))
    print(m)
    print(np.ones((N//2,  N//2+(N%2 == 1))))

In [206]:
f6(15)

[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
